# Context

British Columbia’s Green Sea Urchin (\emph{Strongylocentrotus droebachiensis}) stock is assessed 
every three years using the assessment model developed by @perry2003. The last 
assessment was conducted in 2018 [@dfo2018a] and was used to inform the Pacific Region’s 
Green Sea Urchin 2018-2021 Integrated Fishery Management Plan (IFMP) [@dfo2018b]. The 
present assessment provides updated advice, based on the inclusion of new data, for the 
development of the next IFMP in 2021.

Fisheries and Oceans Canada (DFO) Fisheries Management has requested advice for the 
Green Sea Urchin fishery in British Columbia (BC), by spring 2021, on the following:

1. Evaluate stock status of Green Sea Urchins in Northeast (Pacific Fisheries Management 
Areas - PFMAs: 11, 12, 13) and Southeast Vancouver Island (PFMAs 18, 19, 20) using 
provisional reference points and density estimates derived from biological surveys within 
each management region.

2. Provide the ranges of sustainable harvest options for the commercial harvest regions 
(PFMAs 11, 12 ,13, 18 ,19, 20).

3. Analyze index site survey data (PFMAs 12 and 19) and present the recent trends in the local 
populations and population structure for Green Sea Urchins.

4. Examine and identify uncertainties in the data and methods.

5. Provide recommendations for additional research or stock assessment programs.

This assessment updates previously published time series data and provides new harvest 
options for the 2021-2022 to 2023-2024 Green Sea Urchin fishery. Methods remain unchanged
since 2003 and a Bayesian biomass dynamic model continues to be used in the assessment of 
BC’s Green Sea Urchin stock [@perry2003; @zhang2005; @perry2006; @waddell2010;
@dfo2014; @dfo2016b; @dfo2018a]. This assessment updates the model 
results with the most recently available commercial catch (fishery-dependent) and dive survey 
(fishery-independent) information. Provisional reference points compliant with the DFO’s Fishery 
Decision-Making Framework Incorporating the Precautionary Approach (DFO Precautionary 
Approach; DFO 2009) were established [@dfo2018a] and subsequently implemented in the 
fishery [@dfo2018b]. Using these reference points, Green Sea Urchin stock status can be 
estimated in the regions of Northeast Vancouver Island (PFMAs 11, 12 and 13) and Southeast 
Vancouver Island (18, 19 and 20); the two regions where the long-term index sites are located
(PFMAs 12 and 19). This Science Response results from the June 30, 2021 Regional Science Response Process on 
Stock Stock Status Update and Harvest Options for the Green Sea Urchin  (\emph{Strongylocentrotus droebachiensis})
fishery in British Columbia, 2021-2024